/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_performance_test_nativo_floatoperation_FloatOperationNative */

#ifndef _Included_edu_performance_test_nativo_floatoperation_FloatOperationNative
#define _Included_edu_performance_test_nativo_floatoperation_FloatOperationNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_performance_test_nativo_floatoperation_FloatOperationNative
 * Method:    testNFloatOperationSine
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_edu_performance_test_nativo_floatoperation_FloatOperationNative_testNFloatOperationSine
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     edu_performance_test_nativo_floatoperation_FloatOperationNative
 * Method:    testNFloatOperationSqrt
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_edu_performance_test_nativo_floatoperation_FloatOperationNative_testNFloatOperationSqrt
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     edu_performance_test_nativo_floatoperation_FloatOperationNative
 * Method:    testNFloatOperationMonteCarlo
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_edu_performance_test_nativo_floatoperation_FloatOperationNative_testNFloatOperationMonteCarlo
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     edu_performance_test_nativo_floatoperation_FloatOperationNative
 * Method:    testNFloatOperationLinpack
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_edu_performance_test_nativo_floatoperation_FloatOperationNative_testNFloatOperationLinpack
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     edu_performance_test_nativo_floatoperation_FloatOperationNative
 * Method:    testNFloatOperationCubic
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_edu_performance_test_nativo_floatoperation_FloatOperationNative_testNFloatOperationCubic
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     edu_performance_test_nativo_floatoperation_FloatOperationNative
 * Method:    testNFloatOperationdeg2rad
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_edu_performance_test_nativo_floatoperation_FloatOperationNative_testNFloatOperationdeg2rad
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     edu_performance_test_nativo_floatoperation_FloatOperationNative
 * Method:    testNFloatOperationrad2deg
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_edu_performance_test_nativo_floatoperation_FloatOperationNative_testNFloatOperationrad2deg
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
