/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_performance_test_nativo_stringoperation_StringOperationNative */

#ifndef _Included_edu_performance_test_nativo_stringoperation_StringOperationNative
#define _Included_edu_performance_test_nativo_stringoperation_StringOperationNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_performance_test_nativo_stringoperation_StringOperationNative
 * Method:    testTNMsearchString
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_performance_test_nativo_stringoperation_StringOperationNative_testTNMsearchString
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
