/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_performance_test_nativo_graphicoperation_twod_CircleOperationNativeActivity */

#ifndef _Included_edu_performance_test_nativo_graphicoperation_twod_CircleOperationNativeActivity
#define _Included_edu_performance_test_nativo_graphicoperation_twod_CircleOperationNativeActivity
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
