/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_performance_test_nativo_integeroperation_IntegerOperationNativeActivity */

#ifndef _Included_edu_performance_test_nativo_integeroperation_IntegerOperationNativeActivity
#define _Included_edu_performance_test_nativo_integeroperation_IntegerOperationNativeActivity
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
