/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_performance_test_nativo_graphicoperation_twod_CircleOperationNative */

#ifndef _Included_edu_performance_test_nativo_graphicoperation_twod_CircleOperationNative
#define _Included_edu_performance_test_nativo_graphicoperation_twod_CircleOperationNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_performance_test_nativo_graphicoperation_twod_CircleOperationNative
 * Method:    testNCircleOperation
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_performance_test_nativo_graphicoperation_twod_CircleOperationNative_testNCircleOperation
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
