/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_performance_test_nativo_fileoperation_FileOperationNative */

#ifndef _Included_edu_performance_test_nativo_fileoperation_FileOperationNative
#define _Included_edu_performance_test_nativo_fileoperation_FileOperationNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_performance_test_nativo_fileoperation_FileOperationNative
 * Method:    testNreadSequentialAcessFile
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_edu_performance_test_nativo_fileoperation_FileOperationNative_testNreadSequentialAcessFile
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     edu_performance_test_nativo_fileoperation_FileOperationNative
 * Method:    testNreadRandomAcessFile
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_edu_performance_test_nativo_fileoperation_FileOperationNative_testNreadRandomAcessFile
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     edu_performance_test_nativo_fileoperation_FileOperationNative
 * Method:    testNwriteRandomAcessFile
 * Signature: (Ljava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_performance_test_nativo_fileoperation_FileOperationNative_testNwriteRandomAcessFile
  (JNIEnv *, jobject, jstring, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
