/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_performance_test_nativo_memoryoperation_MemoryOperationNative */

#ifndef _Included_edu_performance_test_nativo_memoryoperation_MemoryOperationNative
#define _Included_edu_performance_test_nativo_memoryoperation_MemoryOperationNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_performance_test_nativo_memoryoperation_MemoryOperationNative
 * Method:    testNallocMemory
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_performance_test_nativo_memoryoperation_MemoryOperationNative_testNallocMemory
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_performance_test_nativo_memoryoperation_MemoryOperationNative
 * Method:    testNcopyMemory
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_performance_test_nativo_memoryoperation_MemoryOperationNative_testNcopyMemory
  (JNIEnv *, jobject);

/*
 * Class:     edu_performance_test_nativo_memoryoperation_MemoryOperationNative
 * Method:    testNfreeMemory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_performance_test_nativo_memoryoperation_MemoryOperationNative_testNfreeMemory
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
