/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_performance_test_nativo_integeroperation_IntegerOperationNative */

#ifndef _Included_edu_performance_test_nativo_integeroperation_IntegerOperationNative
#define _Included_edu_performance_test_nativo_integeroperation_IntegerOperationNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_performance_test_nativo_integeroperation_IntegerOperationNative
 * Method:    testNIntegerOperationSieve
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_performance_test_nativo_integeroperation_IntegerOperationNative_testNIntegerOperationSieve
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_performance_test_nativo_integeroperation_IntegerOperationNative
 * Method:    testNIntegerOperationFibonacci
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_performance_test_nativo_integeroperation_IntegerOperationNative_testNIntegerOperationFibonacci
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_performance_test_nativo_integeroperation_IntegerOperationNative
 * Method:    testNIntegerOperationAckermann
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_performance_test_nativo_integeroperation_IntegerOperationNative_testNIntegerOperationAckermann
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
