/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_performance_test_nativo_fileoperation_FileOperationNativeActivity */

#ifndef _Included_edu_performance_test_nativo_fileoperation_FileOperationNativeActivity
#define _Included_edu_performance_test_nativo_fileoperation_FileOperationNativeActivity
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
