/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_performance_test_nativo_stringoperation_StringOperationNativeActivity */

#ifndef _Included_edu_performance_test_nativo_stringoperation_StringOperationNativeActivity
#define _Included_edu_performance_test_nativo_stringoperation_StringOperationNativeActivity
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
